### ISSUE TITLE
感觉还不错哦。。。提几个优化方案

### ISSUE THREAD

**Issue by zwlcoding** [binnng/debug.js#6]
一个是 position:fixed 在iOS上有bug 。最好使用 position:absolute;

然后呢，能不能设置log最大显示条数，因为我发现log太多之后就看不到下方的log了。超出了多少条之后会删掉前面的比较好。

最后呢。能不能提供一个简单的方法开关 debug。 开发调试的时候使用debug很好用。但是当我要上线项目的时候该怎么办呢，总不能一条条的删除 debug.log("xxx") 吧.....

**Comment by ZhangBohan** [comment]
@binnng 同求加个开关

**Comment by xyjincan** [comment]
function d(x){
    var moble = false;
    moble = true;// 移动端调试输出
    if(debug && moble){
        debug.success(x);
    }else{
        console.log(typeof x +":"+ x);
        console.dir(x);
    }
}
